name: "Deploy"

on:
  push:
    branches:
      - "main"

x-ssh: &ssh
  host: ${{ secrets.HOST }}
  username: ${{ secrets.USERNAME }}
  key: ${{ secrets.KEY }}
  port: ${{ secrets.PORT }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: npm ci
      - run: npm run build
      - name: Remove old data
        uses: appleboy/ssh-action@master
        with:
          <<: *ssh
          script: rm -rf /srv/nms/website/public/*
      - name: Copy files
        uses: appleboy/scp-action@master
        with:
          <<: *ssh
          strip_components: 1
          source: "build"
          target: "/srv/nms/website/public"
