name: Build image

on:
  push:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      # - run: git lfs pull
      - run: ls -hal static/font

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - run: ls -hal static/font
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          # platforms: linux/amd64,linux/arm64
          tags: test/test
          context: .
      - run: docker run --rm test/test ls -hal build/client/font
      - run: ls -hal static/font
